[metadata]
name = foi-search-service
version = 0.0.1
author = alvesfc
author_email = marcos.cunha@bc.gov.ca
description = A service for searching and embedding tokens using various models.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/bcgov/foi-search.git
license = MIT
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    License :: OSI Approved :: MIT License
    Topic :: Scientific/Engineering :: Artificial Intelligence


[options]
packages = find:
package_dir =
    =src
python_requires = >=3.8
install_requires =
    uvicorn[standard]>=0.35.0
    transformers>=4.53.3
    sentence-transformers>=5.0.0
    numpy>=2.3.1
    openai>=1.97.1
    tqdm>=4.67.1
    python-dotenv>=1.1.1
    torch>=2.7.1
    spacy>=3.8.7
    fastapi>=0.116.1
    pydantic>=2.11.7

[options.extras_require]
dev =
    pytest>=8.4.1
    black>=25.1.0
    flake8>=7.3.0
    mypy>=1.17.0
    isort>=6.0.1
    scikit-learn>=1.7.1
    pytest-cov>=6.2.1

[options.package_data]
* = *.txt, *.md

[options.packages.find]
where = src
