name: Deploy all Resources to AZURE environment

on:
  workflow_dispatch: 
    inputs:
      licence:
        description: 'Licence plate (e.g., b21c6d)'
        required: true
        type: string
      environment:
        description: 'Environment (dev, test, prod) (case insensitive).'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set ENV Variables
        run: |
          ENVIRONMENT=$(echo "${{ github.event.inputs.environment }}" | tr '[:lower:]' '[:upper:]')

          case "$ENVIRONMENT" in
            DEV)
              echo "ACTION_ENV=AZURE_CREDENTIALS_DEV" >> $GITHUB_ENV ;;
            TEST)
              echo "ACTION_ENV=AZURE_CREDENTIALS_TEST" >> $GITHUB_ENV ;;
            PROD)
              echo "ACTION_ENV=AZURE_CREDENTIALS_PROD" >> $GITHUB_ENV ;;
            *)
              echo "Invalid environment specified" >&2
              exit 1 ;;
          esac

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.ACTION_ENV] }}

      - name: Deploy Bicep Template
        run: |      
          az deployment group create \
            --resource-group "${{ github.event.inputs.licence }}-${ENVIRONMENT}-networking" \
            --template-file bicep/main.bicep \
            --mode Incremental \
            --parameters @bicep/main.parameters.json \
            --parameters licencePlate="${{ github.event.inputs.licence }}" \
                         environment="$ENVIRONMENT" \
                         subId="${{ secrets[format('SUB_ID_{0}', env.ENVIRONMENT)] }}" \
                         vmAdminUsername="${{ secrets[format('VM_ADMIN_{0}', env.ENVIRONMENT)] }}" \
                         vmAdminPassword="${{ secrets[format('VM_PW_{0}', env.ENVIRONMENT)] }}" \
            --debug
