name: Deploy all Resources to AZURE environment

on:
  workflow_dispatch: 
    inputs:
      licence:
        description: 'Licence plate (e.g., b21c6d)'
        required: true
        type: string
      environment:
        description: 'Environment (dev, test, prod) (case insensitive).'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set ENV Variables
        run: |
          ENVIRONMENT=$(echo "${{ github.event.inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

          case "$ENVIRONMENT" in
            DEV)
              echo "ACTION_ENV=AZURE_CREDENTIALS_DEV" >> $GITHUB_ENV
              echo "SUB_ID=${{ secrets.SUB_ID_DEV }}" >> $GITHUB_ENV
              echo "VM_ADMIN_USERNAME=${{ secrets.VM_ADMIN_DEV }}" >> $GITHUB_ENV
              echo "VM_ADMIN_PASSWORD=${{ secrets.VM_PW_DEV }}" >> $GITHUB_ENV
              ;;
            TEST)
              echo "ACTION_ENV=AZURE_CREDENTIALS_TEST" >> $GITHUB_ENV
              echo "SUB_ID=${{ secrets.SUB_ID_TEST }}" >> $GITHUB_ENV
              echo "VM_ADMIN_USERNAME=${{ secrets.VM_ADMIN_TEST }}" >> $GITHUB_ENV
              echo "VM_ADMIN_PASSWORD=${{ secrets.VM_PW_TEST }}" >> $GITHUB_ENV
              ;;
            PROD)
              echo "ACTION_ENV=AZURE_CREDENTIALS_PROD" >> $GITHUB_ENV
              echo "SUB_ID=${{ secrets.SUB_ID_PROD }}" >> $GITHUB_ENV
              echo "VM_ADMIN_USERNAME=${{ secrets.VM_ADMIN_PROD }}" >> $GITHUB_ENV
              echo "VM_ADMIN_PASSWORD=${{ secrets.VM_PW_PROD }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment specified" >&2
              exit 1 ;;
          esac

          # Set Resource Group
          RESOURCE_GROUP="${{ github.event.inputs.licence }}-${ENVIRONMENT}-networking"
          echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV

      
      - name: Deploy Bicep Template
        run: |
          ENVIRONMENT_LOWER=$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')
          az deployment group create \
            --resource-group "$RESOURCE_GROUP" \
            --template-file bicep/main.bicep \
            --mode Incremental \
            --parameters @bicep/main.parameters.json \
            --parameters licencePlate="${{ github.event.inputs.licence }}" \
                         environment="$ENVIRONMENT_LOWER" \
                         subId="$SUB_ID" \
                         vmAdminUsername="$VM_ADMIN_USERNAME" \
                         vmAdminPassword="$VM_ADMIN_PASSWORD" \
            --debug
